name: CI TiendaOnline

on:
  push:
    branches: [ main, feature-tests ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Descargar c√≥digo
      uses: actions/checkout@v4

    - name: 2. Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 3. Restaurar paquetes NuGet
      run: dotnet restore

    - name: 4. Compilar proyecto
      run: dotnet build --no-restore

    - name: 5. Ejecutar Tests
      run: dotnet test --no-build --verbosity normal